// package controller;

// import javafx.fxml.FXML;
// import javafx.scene.control.Button;
// import javafx.scene.layout.HBox;
// import javafx.event.ActionEvent;
// import javafx.scene.control.Label;
// import javafx.scene.control.CheckBox;
// import javafx.util.StringConverter;
// import model.Answers;
// import model.Exam;
// import model.HostExam;
// import model.Question;
// import javafx.scene.layout.VBox;
// import java.io.IOException;
// import java.util.List;

// import javafx.scene.Node;
// import utils.Notification;
// import javafx.scene.Parent;

// public class ClientExamController {
// @FXML
// private VBox QuestionsVbox;
// @FXML
// private VBox answerVbox;
// @FXML
// private HBox questionHbox;
// @FXML
// private Button btnQuestion;
// @FXML
// private Label tfQuestion;
// @FXML
// private Label subjName;
// @FXML
// private Label examName;
// @FXML
// private Label lbScore;
// @FXML
// private Label lb_InfEx;
// @FXML
// private Button btnExport;
// @FXML
// private Button btnSubmit;
// @FXML
// private Label lbClock;

// // load exam
// Exam exam = new Exam();
// String oldId = "#";

// public void initExam(HostExam exam) {
// try {
// // Hiển thị bảng điều khiển câu hỏi
// List<Integer> listQuest = exam.getQuestionsIds();
// for (int i = 1; i <= listQuest.size(); i++) {
// Button button = new Button(String.valueOf(i));
// button.setId("btnQuestion" + i);
// button.getStyleClass().add("button-xanhnhat");
// button.setOnAction(this::btnQuestionClicked);
// if (i % 2 == 1) {
// HBox hbox = new HBox();
// hbox.setId("hboxQuestion" + ((i / 2) + 1));
// QuestionsVbox.getChildren().add(hbox);
// }
// HBox root = (HBox) QuestionsVbox.lookup("#hboxQuestion" + ((i / 2) + 1));
// root.getChildren().add(button);
// }
// // Mặc định hiển thị câu hỏi 1
// oldId = "#btnQuestion1";
// Button btn = (Button) QuestionsVbox.lookup(oldId);
// btn.setStyle("-fx-background-color:#ffffff,-fx-text-fill:#154FEF,-fx-border-color:#154FEF");
// tfQuestion.setText("Câu 1:" + listQuest.get(0).getContent());
// for (int i = 1; i <= listQuest.get(0).getAnswers().size(); i++) {
// HBox hbox = new HBox();
// hbox.setId("answerHbox" + i);
// answerVbox.getChildren().add(hbox);
// CheckBox check = new CheckBox();
// check.setId("ck" + i);
// hbox.getChildren().add(check);
// check.setSelected(false);
// Label answerContent = new Label();
// answerContent.setId("answer" + i);
// hbox.getChildren().add(answerContent);
// answerContent.setText(listQuest.get(0).getAnswers().get(i - 1).getContent());
// }
// } catch (Exception e) {
// Notification.Error("Error", "Cannot load exam!", null);
// }
// }

// public void btnQuestionClicked(ActionEvent event) {
// Button button = (Button) event.getSource();
// QuestionsVbox.lookup(oldId).setStyle("");
// oldId = "#" + button.getId();
// button.setStyle("-fx-background-color:#ffffff,-fx-text-fill:#154FEF,-fx-border-color:#154FEF");
// int questId = Integer.parseInt(btnQuestion.getText());
// for (Question question : exam.getQuestions()) {
// if (question.getQuestionId() == questId) {
// tfQuestion.setText("Câu " + questId + ": " + question.getContent());
// answerVbox.getChildren().clear();
// int i = 1;
// for (Answers answer : question.getAnswers()) {
// HBox hbox = new HBox();
// hbox.setId("answerHbox" + i);
// answerVbox.getChildren().add(hbox);
// CheckBox check = new CheckBox();
// check.setId("ck" + i);
// hbox.getChildren().add(check);
// check.setSelected(false);
// Label answerContent = new Label(question.getAnswers().get(i -
// 1).getContent());
// answerContent.setId("answer" + i);
// hbox.getChildren().add(answerContent);
// i++;
// }
// }
// }
// }

// public void btnExportClicked(ActionEvent event) {
// // TODO Autogenerated
// }

// // Event Listener on Button[#btnSubmit].onAction
// @FXML
// public void btnSubmitClicked(ActionEvent event) {
// // TODO Autogenerated
// }
// }
